# 系统配置
system:
  # 注册
  register:
    # 是否允许注册
    enable: true
    # 是否启用注册码
    invitationCode: false

# 数据库配置
db:
  type: mysql # 使用的数据库类型，可选 mysql | postgresql
  host: mysql # 数据库地址(使用docker-compose启动可以不用改)
  port: 3306 # 数据库端口
  username: pixiu # 数据库用户名
  password: pixiu # 数据库密码
  database: pixiu # 数据库名

# Redis配置
redis:
  host: redis # Redis地址(使用docker-compose启动可以不用改)
  port: 6379 # Redis端口
  password: mNhgeSk32fUf69C6
  db: 0

# 青龙配置
ql:
  host: http://10.0.0.52:5700
  clientId: xxx
  clientSecret: xxx

# BBK配置
bbk:
  jdQr:
    enable: true
    host: http://bbk-jd-qr:81
  # 下面两种还没实现
  wechatQr:
    enable: false
    host: http://10.0.0.52:5702
  sms:
    enable: false
    host: http://10.0.0.52:5703

# 通知配置
notify:
  allowTitle:
    - 东东农场日常任务
    - 京东资产变动
    - 京东价保
  wechat:
    # 微信HOOK，自行使用wxhelper搭建
    enable: false
    qrCode: xxx # 这儿填添加好友的二维码解码后的内容，解码可以在草料二维码解码：https://cli.im/deqr/other
    # 接口请求地址
    host: http://10.0.0.71:19088
    # 手动设置回调地址(不写会默认取本机IP+服务端口组装，如果在容器内，可能会导致回调地址无法访问)
    callback: http://10.11.0.2:1323/api/v1/notify/wechat
  qq:
    # QQ机器人，自行使用go-cqhttp搭建
    enable: false
    qrCode: xxx # 这儿填添加好友的二维码解码后的内容，解码可以在草料二维码解码：https://cli.im/deqr/other
    host: http://10.0.0.52:2333
    accessToken: xxx
  ftqq:
    # 方糖气球，又叫Server酱
    enable: true
  pushDeer:
    # PushDeer
    enable: true
    host: # 自建服务器地址，为空则使用官方地址(https://api2.pushdeer.com/message/push)
  pushPlus:
    # PushPlus
    enable: true
  smtp:
    # 邮件
    enable: true
    host: smtp.qq.com
    ssl: true
    email: xx
    password: xx