# 数据库配置
db:
  type: mysql # 使用的数据库类型，可选 mysql | postgresql
  host: 10.0.0.31 # 数据库地址
  port: 3306 # 数据库端口
  username: pixiu # 数据库用户名
  password: pixiu123 # 数据库密码
  database: pixiu # 数据库名

# Redis配置
redis:
  host: 10.0.0.31
  port: 6379
  password: xxx
  db: 0

# 青龙配置
ql:
  host: http://10.0.0.52:5700
  clientId: xxx
  clientSecret: xxx

# BBK配置
bbk:
  jdQr:
    enable: true
    host: http://10.0.0.52:5701
  wechatQr:
    enable: true
    host: http://10.0.0.52:5702
  sms:
    enable: true
    host: http://10.0.0.52:5703

# 通知配置
notify:
  allowTitle:
    - 东东农场日常任务
    - 京东资产变动
  wechat:
    host: http://10.0.0.71:19088
  qq:
    host: http://10.0.0.52:2333
    accessToken: xxx